### PR TITLE
Rotating Encryption Keys Implication Warning

### PR DESCRIPTION
**Pull request by nrdevau**
There's considerable discussion on Slack around this and it seems like something should be raised on the developer centric guide for applying this patch

https://magentocommeng.slack.com/archives/CANPJTBC5/p1721712368965519 and
https://magentocommeng.slack.com/archives/CANPJTBC5/p1721777445258809

Whoever reviews this is probably already in the chat, but it's good to have context

Note: I have no way of building the kb locally, so this is all untested, but hopefully working

### CODE REVIEW

**Comment by nrdevau** [comment]
There's a lengthy discussion in slack for anyone interested.. If updating the patch notes is not the right place, can we get some sort of deliverable that talks to the implications of re-encryption (even ignoring the security risk, just the technical impact) so businesses can see, "oh, doing this will mean potentially 3 days of downtime...."?

**Comment by nrdevau** [comment]
Further discussion https://www.gene.co.uk/fix-the-critical-adobe-magento-security-vulnerability-with-our-latest-module/

**Comment by nrdevau** [comment]
Annnd more discussion https://github.com/magento/magento2/pull/38963
This is a big thing, and it seems Adobe are deciding to address it internally rather than accepting community driven efforts.. It's a shame, but the doc PR isn't the right place for a retro ;)

**Comment by TuVanDev** [comment]
I fully support this proposal. Highlighting the impact of rotating encryption keys through the admin panel is crucial, as the current implementation does not fully handle the re-encryption of encrypted data. This issue is especially problematic for sites with a large number of product images, leading to site downtime due to the regeneration of image caches.

Even if Adobe cannot recommend a community module to address this, it is still important to acknowledge and address the impact of rotating encryption keys through the admin panel.

cc @jeff-matthews @nathanjosiah

**Comment by tanay-sharma** [comment]
@nrdevau, thank you for your submission. I have created a [Jira](https://jira.corp.adobe.com/browse/MSKB-2668) for this.

**Comment by nrdevau** [comment]
It's out of my hands now, thanks @tanay-sharma  I will close this as I'm sure internally you will have a much better solution. Thank you for not just shutting it down

**Pull request closed without merging**
